The AM_AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
The AM_AWS_DEFAULT_REGION variable is not set. Defaulting to a blank string.
The AM_AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
The AM_FORCE_TEST_FAIL variable is not set. Defaulting to a blank string.
The AM_TELEGRAM_TOKEN variable is not set. Defaulting to a blank string.
The CK_AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
The CK_AWS_DEFAULT_REGION variable is not set. Defaulting to a blank string.
The CK_AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
The CK_TELEGRAM_TOKEN variable is not set. Defaulting to a blank string.
Creating compose_linter_run ... 
Creating compose_linter_run ... done
##> devops/docker_run/entrypoint.sh
UID=1000
GID=1000
# Activate environment
##> /app/devops/docker_run/setenv.sh
# Set PATH
PATH=/app:/app/linters:/app/dev_scripts_devto/notebooks:/app/documentation_devto/scripts:/app/amp/documentation/scripts:/app/amp/dev_scripts/testing:/app/amp/dev_scripts/notebooks:/app/amp/dev_scripts/install:/app/amp/dev_scripts/infra:/app/amp/dev_scripts/git:/app/amp/dev_scripts/aws:/app/amp/dev_scripts:/app/amp:.:/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# Set PYTHONPATH
PYTHONPATH=/app:/app/amp:
# Configure env
git --version: git version 2.25.1
/src
[33mWARNING[0m: AWS credential check failed: can't find /home/.aws/credentials file.
[33mWARNING[0m: AWS credential check failed: can't find /home/.aws/config file.
# Check AWS authentication setup
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                       am           manual    --profile

The config profile (am) could not be found
AM_CONTAINER_VERSION='1.2.0'
which python: /venv/bin/python
python -V: Python 3.8.10
pandas: 1.4.3
helpers: <module 'helpers' from '/src/helpers/__init__.py'>
PATH=/app:/app/linters:/app/dev_scripts_devto/notebooks:/app/documentation_devto/scripts:/app/amp/documentation/scripts:/app/amp/dev_scripts/testing:/app/amp/dev_scripts/notebooks:/app/amp/dev_scripts/install:/app/amp/dev_scripts/infra:/app/amp/dev_scripts/git:/app/amp/dev_scripts/aws:/app/amp/dev_scripts:/app/amp:.:/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PYTHONPATH=/app:/app/amp:
entrypoint.sh: 'pre-commit run -c /app/.pre-commit-config.yaml --files helpers/hunit_test.py helpers/test/test_unit_test.py'
One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
[0m[36mINFO[0m: > cmd='/venv/bin/invoke print_env'
report_memory_usage=False report_cpu_usage=False
09:31:47 - [41mWARN [0m henv.py get_repo_config_file:485                       Using value '/app/repo_config.py' for AM_REPO_CONFIG_PATH from env var
09:31:47 - [41mWARN [0m <string> _raise_invalid_host:148                       Don't recognize host: host_os_name=Linux, am_host_os_name=Linux
09:31:47 - [41mWARN [0m <string> _raise_invalid_host:148                       Don't recognize host: host_os_name=Linux, am_host_os_name=Linux
09:31:47 - [41mWARN [0m <string> _raise_invalid_host:148                       Don't recognize host: host_os_name=Linux, am_host_os_name=Linux
[31m-----------------------------------------------------------------------------
This code is not in sync with the container:
code_version='1.4.3' != container_version='1.2.0'
-----------------------------------------------------------------------------
You need to:
- merge origin/master into your branch with `invoke git_merge_master`
- pull the latest container with `invoke docker_pull`[0m
# Repo config:
  enable_privileged_mode='False'
  get_docker_base_image_name='dev_tools'
  get_docker_shared_group=''
  get_docker_user=''
  get_host_name='github.com'
  get_invalid_words='[]'
  get_name='//dev_tools'
  get_repo_map='{'cm': 'cryptokaizen/cmamp'}'
  get_shared_data_dirs='None'
  has_dind_support='False'
  has_docker_sudo='False'
  is_AM_S3_available='True'
  is_CK_S3_available='True'
  is_dev4='False'
  is_dev_ck='False'
  is_inside_ci='False'
  is_inside_docker='True'
  is_mac='False'
  run_docker_as_root='False'
  skip_submodules_test='True'
  use_docker_network_mode_host='False'
  use_docker_sibling_containers='False'
# System signature:
  # Git
    branch_name='SorrTask446_Handle_user_name_purification_outliers'
    hash='2a192e7b7'
    # Last commits:
      * 2a192e7b7 dreamcatcher0101 refactor: modified purify_from_environment function to handle username purification outliers (   4 hours ago) Thu Jul 27 09:50:11 2023  (HEAD -> SorrTask446_Handle_user_name_purification_outliers, origin/SorrTask446_Handle_user_name_purification_outliers)
      * 8f557a920 hhxjqm   SorrTask370_Invoke_Tasks_Doesnt_Work_From_Sorrentum (#431)        (    3 days ago) Mon Jul 24 23:31:21 2023  (origin/SorrTask283_Create_test_list_to_run_with_Sorrentum)
      * d97111d0e Sonaal   add unit test plot_heatmap #443 (#448)                            (    3 days ago) Mon Jul 24 20:04:35 2023           
  # Machine info
    system=Linux
    node name=35598b3087de
    release=5.4.0-152-generic
    version=#169-Ubuntu SMP Tue Jun 6 22:23:09 UTC 2023
    machine=x86_64
    processor=x86_64
    cpu count=6
    cpu freq=scpufreq(current=2794.748, min=0.0, max=0.0)
    memory=svmem(total=16773820416, available=11682353152, percent=30.4, used=4581801984, free=10646646784, active=5065809920, inactive=364285952, buffers=48676864, cached=1496694784, shared=176615424, slab=543182848)
    disk usage=sdiskusage(total=102974414848, used=72153096192, free=25543262208, percent=73.9)
  # Packages
    python: 3.8.10
    cvxopt: ?
    cvxpy: ?
    gluonnlp: ?
    gluonts: ?
    joblib: 0.16.0
    mxnet: ?
    numpy: 1.23.0
    pandas: 1.4.3
    pyarrow: ?
    scipy: 1.6.1
    seaborn: ?
    sklearn: ?
    statsmodels: 0.13.2
# Env vars:
  AM_AWS_ACCESS_KEY_ID=undef
  AM_AWS_DEFAULT_REGION=undef
  AM_AWS_PROFILE='am'
  AM_AWS_S3_BUCKET='alphamatic-data'
  AM_AWS_SECRET_ACCESS_KEY=undef
  AM_ECR_BASE_PATH='665840871993.dkr.ecr.us-east-1.amazonaws.com'
  AM_ENABLE_DIND='0'
  AM_FORCE_TEST_FAIL=''
  AM_HOST_NAME='vmi1240441.contaboserver.net'
  AM_HOST_OS_NAME='Linux'
  AM_HOST_USER_NAME='dash'
  AM_HOST_VERSION='5.4.0-152-generic'
  AM_REPO_CONFIG_CHECK='True'
  AM_REPO_CONFIG_PATH='/app/repo_config.py'
  AM_TELEGRAM_TOKEN=empty
  CI=''
  CK_AWS_ACCESS_KEY_ID=empty
  CK_AWS_DEFAULT_REGION=''
  CK_AWS_S3_BUCKET='cryptokaizen-data'
  CK_AWS_SECRET_ACCESS_KEY=empty
  CK_ECR_BASE_PATH='sorrentum'
  GH_ACTION_ACCESS_TOKEN=empty

Check for merge conflicts................................................Passed
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing helpers/test/test_unit_test.py

Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing helpers/test/test_unit_test.py

Check for added large files..............................................Passed
CRLF end-lines remover...................................................Passed
Tabs remover.............................................................Passed
autoflake................................................................Passed
add_python_init_files....................................................Passed
amp_lint_md..........................................(no files to check)Skipped
amp_doc_formatter........................................................Passed
amp_isort................................................................Failed
- hook id: amp_isort
- files were modified by this hook

One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
[0m[36mINFO[0m: > cmd='/app/linters/amp_isort.py helpers/hunit_test.py helpers/test/test_unit_test.py'
report_memory_usage=False report_cpu_usage=False

amp_class_method_order...................................................Failed
- hook id: amp_class_method_order
- files were modified by this hook

One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
[0m[36mINFO[0m: > cmd='/app/linters/amp_class_method_order.py helpers/hunit_test.py helpers/test/test_unit_test.py'
report_memory_usage=False report_cpu_usage=False

amp_normalize_import.....................................................Passed
amp_format_separating_line...............................................Passed
amp_black................................................................Failed
- hook id: amp_black
- files were modified by this hook

One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
[0m[36mINFO[0m: > cmd='/app/linters/amp_black.py helpers/hunit_test.py helpers/test/test_unit_test.py'
report_memory_usage=False report_cpu_usage=False

amp_processjupytext......................................................Passed
amp_check_filename.......................................................Passed
amp_warn_incorrectly_formatted_todo......................................Passed
amp_flake8...............................................................Failed
- hook id: amp_flake8
- exit code: 1

One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
[0m[36mINFO[0m: > cmd='/app/linters/amp_flake8.py helpers/hunit_test.py helpers/test/test_unit_test.py'
report_memory_usage=False report_cpu_usage=False
helpers/hunit_test.py:553:31: W605 invalid escape sequence '\d'

amp_pylint...............................................................Failed
- hook id: amp_pylint
- exit code: 9

One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
[0m[36mINFO[0m: > cmd='/app/linters/amp_pylint.py helpers/hunit_test.py helpers/test/test_unit_test.py'
report_memory_usage=False report_cpu_usage=False
************* Module helpers.hunit_test
helpers/hunit_test.py:553: [W1401(anomalous-backslash-in-string), ] Anomalous backslash in string: '\d'. String constant might be missing an r prefix.
helpers/hunit_test.py:228: [C0209(consider-using-f-string), to_string] Formatting a regular string which could be a f-string
helpers/hunit_test.py:434: [W0621(redefined-outer-name), purify_from_environment] Redefining name 're' from outer scope (line 15)
helpers/hunit_test.py:434: [W0404(reimported), purify_from_environment] Reimport 're' (imported line 15)
helpers/hunit_test.py:898: [E1206(logging-too-few-args), assert_equal._append] Not enough arguments for logging format string
helpers/hunit_test.py:1004: [C0209(consider-using-f-string), assert_equal] Formatting a regular string which could be a f-string
helpers/hunit_test.py:1085: [C0209(consider-using-f-string), TestCase.tearDown] Formatting a regular string which could be a f-string
helpers/hunit_test.py:1798: [C0209(consider-using-f-string), TestCase._check_df_compare_outcome] Formatting a regular string which could be a f-string

amp_mypy.................................................................Failed
- hook id: amp_mypy
- exit code: 11

One and only one set-up config should be true:
is_cmamp_prod=False
is_dev4=False
is_dev_ck=False
is_ig_prod=False
is_inside_ci=False
is_mac=False
[0m[36mINFO[0m: > cmd='/app/linters/amp_mypy.py helpers/hunit_test.py helpers/test/test_unit_test.py'
report_memory_usage=False report_cpu_usage=False
helpers/hunit_test.py:900: error: Incompatible types in assignment (expression has type "Tuple[str, str]", target has type "str")  [assignment]
helpers/hunit_test.py:1003: error: Unpacking a string is disallowed  [misc]
helpers/hunit_test.py:1005: error: Cannot determine type of 'actual_tmp'  [has-type]
helpers/hunit_test.py:1005: error: Cannot determine type of 'expected_tmp'  [has-type]
helpers/hunit_test.py:1008: error: Unpacking a string is disallowed  [misc]
helpers/hunit_test.py:1009: error: Cannot determine type of 'actual_tmp'  [has-type]
helpers/hunit_test.py:1009: error: Cannot determine type of 'expected_tmp'  [has-type]
helpers/hunit_test.py:1365: error: Function is missing a type annotation for one or more arguments  [no-untyped-def]
helpers/hunit_test.py:1797: error: Need type annotation for 'max_err'  [var-annotated]
helpers/test/test_unit_test.py:1214: error: Argument 1 to "helper" of "Test_purify_from_environment1" has incompatible type "Tuple[str]"; expected "str"  [arg-type]
helpers/test/test_unit_test.py:1214: error: Argument 2 to "helper" of "Test_purify_from_environment1" has incompatible type "Tuple[str]"; expected "str"  [arg-type]

1
